In [26]:
## Start pandas

import pandas as pd

## import dataframe csv

df = pd.read_csv('LIF Ashland Nit 12-13-18.csv')

print(type(df))

## rename columns for easy manipulation

df.rename(columns = {'Sample Name':'A', '410 nm   [A]':'B'}, inplace=True)
df

## group csv by desired column

g = df.groupby('A')


## adding a column and assigning value

df['C'] = (g.mean())

## converting column with values to series in dataframe for manipulation

df['B'] = pd.to_numeric(df['B'])

## TO LIST EACH GROUP SEPARATELY...

for key, item in g:
    print(g.get_group(key), "\n\n")

<class 'pandas.core.frame.DataFrame'>
   A      B   C
4  0  0.006 NaN
5  0  0.006 NaN
6  0  0.006 NaN


      A      B   C
7  1500  0.166 NaN
8  1500  0.171 NaN
9  1500  0.166 NaN


     A      B   C
0  1_1  0.004 NaN


     A      B   C
1  1_2  0.003 NaN


     A      B   C
2  2_1  0.001 NaN


     A      B   C
3  2_2  0.003 NaN


       A      B   C
10  3000  0.302 NaN
11  3000  0.300 NaN
12  3000  0.299 NaN


       A      B   C
13  4500  0.437 NaN
14  4500  0.448 NaN
15  4500  0.545 NaN


          A      B   C
16  LIF-241  1.181 NaN
17  LIF-241  1.193 NaN


          A      B   C
18  LIF-242  1.101 NaN
19  LIF-242  1.143 NaN


          A      B   C
20  LIF-243  1.414 NaN
21  LIF-243  1.367 NaN


          A      B   C
22  LIF-244  1.185 NaN
23  LIF-244  1.229 NaN


          A      B   C
24  LIF-245  1.074 NaN
25  LIF-245  1.077 NaN


          A      B   C
26  LIF-246  1.466 NaN
27  LIF-246  1.604 NaN


          A      B   C
28  LIF-247  1.438 NaN
29  LIF-247  1.401 NaN


          A      B   C
30  LIF-248  1.564 NaN
31  LIF-248  1.575 NaN


          A      B   C
32  LIF-249  1.282 NaN
33  LIF-249  1.302 NaN


          A      B   C
34  LIF-250  1.038 NaN
35  LIF-250  1.125 NaN


          A      B   C
36  LIF-251  1.226 NaN
37  LIF-251  1.128 NaN


          A      B   C
38  LIF-252  1.256 NaN
39  LIF-252  1.184 NaN


          A      B   C
40  LIF-253  1.335 NaN
41  LIF-253  1.462 NaN


          A      B   C
42  LIF-254  1.114 NaN
43  LIF-254  1.125 NaN


          A      B   C
44  LIF-255  1.092 NaN
45  LIF-255  1.059 NaN


          A      B   C
46  LIF-256  1.124 NaN
47  LIF-256  1.102 NaN


          A      B   C
48  LIF-257  1.208 NaN
49  LIF-257  1.279 NaN


          A      B   C
50  LIF-258  0.674 NaN
51  LIF-258  0.681 NaN


          A      B   C
52  LIF-259  0.663 NaN
53  LIF-259  0.672 NaN


          A      B   C
54  LIF-260  0.824 NaN
55  LIF-260  0.794 NaN


          A      B   C
56  LIF-261  0.648 NaN
57  LIF-261  0.675 NaN


          A      B   C
58  LIF-262  0.759 NaN
59  LIF-262  0.792 NaN


          A      B   C
60  LIF-263  0.562 NaN
61  LIF-263  1.099 NaN


          A      B   C
62  LIF-264  0.871 NaN
63  LIF-264  0.847 NaN


          A      B   C
64  LIF-265  0.944 NaN
65  LIF-265  0.951 NaN


          A      B   C
66  LIF-266  0.785 NaN
67  LIF-266  0.780 NaN


          A      B   C
68  LIF-267  0.665 NaN
69  LIF-267  0.659 NaN


          A      B   C
70  LIF-268  0.968 NaN
71  LIF-268  0.969 NaN

In [41]:
print(type(g.mean()))

## converting column with values to series in dataframe for manipulation

g.mean()['B'] = pd.to_numeric(g.mean()['B'])
print(type(g.mean()))

print(g.mean())

## exporting means as new .csv file

g.mean().to_csv('Means.csv')

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
                B
A
0        0.006000
1500     0.167667
1_1      0.004000
1_2      0.003000
2_1      0.001000
2_2      0.003000
3000     0.300333
4500     0.476667
LIF-241  1.187000
LIF-242  1.122000
LIF-243  1.390500
LIF-244  1.207000
LIF-245  1.075500
LIF-246  1.535000
LIF-247  1.419500
LIF-248  1.569500
LIF-249  1.292000
LIF-250  1.081500
LIF-251  1.177000
LIF-252  1.220000
LIF-253  1.398500
LIF-254  1.119500
LIF-255  1.075500
LIF-256  1.113000
LIF-257  1.243500
LIF-258  0.677500
LIF-259  0.667500
LIF-260  0.809000
LIF-261  0.661500
LIF-262  0.775500
LIF-263  0.830500
LIF-264  0.859000
LIF-265  0.947500
LIF-266  0.782500
LIF-267  0.662000
LIF-268  0.968500

In [43]:
## importing new dataframe

df2 = pd.read_csv("Means.csv")
df2

          A         B
0         0  0.006000
1      1500  0.167667
2       1_1  0.004000
3       1_2  0.003000
4       2_1  0.001000
5       2_2  0.003000
6      3000  0.300333
7      4500  0.476667
8   LIF-241  1.187000
9   LIF-242  1.122000
10  LIF-243  1.390500
11  LIF-244  1.207000
12  LIF-245  1.075500
13  LIF-246  1.535000
14  LIF-247  1.419500
15  LIF-248  1.569500
16  LIF-249  1.292000
17  LIF-250  1.081500
18  LIF-251  1.177000
19  LIF-252  1.220000
20  LIF-253  1.398500
21  LIF-254  1.119500
22  LIF-255  1.075500
23  LIF-256  1.113000
24  LIF-257  1.243500
25  LIF-258  0.677500
26  LIF-259  0.667500
27  LIF-260  0.809000
28  LIF-261  0.661500
29  LIF-262  0.775500
30  LIF-263  0.830500
31  LIF-264  0.859000
32  LIF-265  0.947500
33  LIF-266  0.782500
34  LIF-267  0.662000
35  LIF-268  0.968500

In [68]:
#for key, item in g:
#    g.get_group(key)['C'] = df2["B"]

#df

for key, item in g: 
    print(g.get_group(key), "\n\n")
    if    
    
df

## NEXT STEP _ ASSIGNING VALUES FROM ONE DATASET TO ANOTHER >>> BASED ON ID VALUE

TypeError: 'DataFrameGroupBy' object does not support item assignment

In [50]:
(g.get_group(key), "\n\n")

(          A      B   C
 70  LIF-268  0.968 NaN
 71  LIF-268  0.969 NaN, '\n\n')