In [34]:
## Start pandas

import pandas as pd

## import dataframe csv

df = pd.read_csv('LIF Ashland Nit 12-13-18.csv')

print(type(df))

## rename columns for easy manipulation

df.rename(columns = {'Sample Name':'A', '410 nm   [A]':'B'}, inplace=True)
df

## group csv by desired column

g = df.groupby('A')


## converting column with values to series in dataframe for manipulation

df['B'] = pd.to_numeric(df['B'])

## TO LIST EACH GROUP SEPARATELY...

# for key, item in g:
#    print(g.get_group(key), "\n\n")

<class 'pandas.core.frame.DataFrame'>

In [23]:
print(type(g.mean()))

## converting column with values to series in dataframe for manipulation

g.mean()['B'] = pd.to_numeric(g.mean()['B'])
print(type(g.mean()))

print(g.mean())

## exporting means as new .csv file

g.mean().to_csv('Means.csv')

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
                B
A
0        0.006000
1500     0.167667
1_1      0.004000
1_2      0.003000
2_1      0.001000
2_2      0.003000
3000     0.300333
4500     0.476667
LIF-241  1.187000
LIF-242  1.122000
LIF-243  1.390500
LIF-244  1.207000
LIF-245  1.075500
LIF-246  1.535000
LIF-247  1.419500
LIF-248  1.569500
LIF-249  1.292000
LIF-250  1.081500
LIF-251  1.177000
LIF-252  1.220000
LIF-253  1.398500
LIF-254  1.119500
LIF-255  1.075500
LIF-256  1.113000
LIF-257  1.243500
LIF-258  0.677500
LIF-259  0.667500
LIF-260  0.809000
LIF-261  0.661500
LIF-262  0.775500
LIF-263  0.830500
LIF-264  0.859000
LIF-265  0.947500
LIF-266  0.782500
LIF-267  0.662000
LIF-268  0.968500

In [24]:
## importing new dataframe

df2 = pd.read_csv("Means.csv")
df2

          A         B
0         0  0.006000
1      1500  0.167667
2       1_1  0.004000
3       1_2  0.003000
4       2_1  0.001000
5       2_2  0.003000
6      3000  0.300333
7      4500  0.476667
8   LIF-241  1.187000
9   LIF-242  1.122000
10  LIF-243  1.390500
11  LIF-244  1.207000
12  LIF-245  1.075500
13  LIF-246  1.535000
14  LIF-247  1.419500
15  LIF-248  1.569500
16  LIF-249  1.292000
17  LIF-250  1.081500
18  LIF-251  1.177000
19  LIF-252  1.220000
20  LIF-253  1.398500
21  LIF-254  1.119500
22  LIF-255  1.075500
23  LIF-256  1.113000
24  LIF-257  1.243500
25  LIF-258  0.677500
26  LIF-259  0.667500
27  LIF-260  0.809000
28  LIF-261  0.661500
29  LIF-262  0.775500
30  LIF-263  0.830500
31  LIF-264  0.859000
32  LIF-265  0.947500
33  LIF-266  0.782500
34  LIF-267  0.662000
35  LIF-268  0.968500

In [25]:
#for key, item in g:
#    g.get_group(key)['C'] = df2["B"]

#df

for key, item in g: 
    print(g.get_group(key), "\n\n")

df

## NEXT STEP _ ASSIGNING VALUES FROM ONE DATASET TO ANOTHER >>> BASED ON ID VALUE

   A      B
4  0  0.006
5  0  0.006
6  0  0.006


      A      B
7  1500  0.166
8  1500  0.171
9  1500  0.166


     A      B
0  1_1  0.004


     A      B
1  1_2  0.003


     A      B
2  2_1  0.001


     A      B
3  2_2  0.003


       A      B
10  3000  0.302
11  3000  0.300
12  3000  0.299


       A      B
13  4500  0.437
14  4500  0.448
15  4500  0.545


          A      B
16  LIF-241  1.181
17  LIF-241  1.193


          A      B
18  LIF-242  1.101
19  LIF-242  1.143


          A      B
20  LIF-243  1.414
21  LIF-243  1.367


          A      B
22  LIF-244  1.185
23  LIF-244  1.229


          A      B
24  LIF-245  1.074
25  LIF-245  1.077


          A      B
26  LIF-246  1.466
27  LIF-246  1.604


          A      B
28  LIF-247  1.438
29  LIF-247  1.401


          A      B
30  LIF-248  1.564
31  LIF-248  1.575


          A      B
32  LIF-249  1.282
33  LIF-249  1.302


          A      B
34  LIF-250  1.038
35  LIF-250  1.125


          A      B
36  LIF-251  1.226
37  LIF-251  1.128


          A      B
38  LIF-252  1.256
39  LIF-252  1.184


          A      B
40  LIF-253  1.335
41  LIF-253  1.462


          A      B
42  LIF-254  1.114
43  LIF-254  1.125


          A      B
44  LIF-255  1.092
45  LIF-255  1.059


          A      B
46  LIF-256  1.124
47  LIF-256  1.102


          A      B
48  LIF-257  1.208
49  LIF-257  1.279


          A      B
50  LIF-258  0.674
51  LIF-258  0.681


          A      B
52  LIF-259  0.663
53  LIF-259  0.672


          A      B
54  LIF-260  0.824
55  LIF-260  0.794


          A      B
56  LIF-261  0.648
57  LIF-261  0.675


          A      B
58  LIF-262  0.759
59  LIF-262  0.792


          A      B
60  LIF-263  0.562
61  LIF-263  1.099


          A      B
62  LIF-264  0.871
63  LIF-264  0.847


          A      B
64  LIF-265  0.944
65  LIF-265  0.951


          A      B
66  LIF-266  0.785
67  LIF-266  0.780


          A      B
68  LIF-267  0.665
69  LIF-267  0.659


          A      B
70  LIF-268  0.968
71  LIF-268  0.969

          A      B
0       1_1  0.004
1       1_2  0.003
2       2_1  0.001
3       2_2  0.003
4         0  0.006
5         0  0.006
6         0  0.006
7      1500  0.166
8      1500  0.171
9      1500  0.166
10     3000  0.302
11     3000  0.300
12     3000  0.299
13     4500  0.437
14     4500  0.448
15     4500  0.545
16  LIF-241  1.181
17  LIF-241  1.193
18  LIF-242  1.101
19  LIF-242  1.143
20  LIF-243  1.414
21  LIF-243  1.367
22  LIF-244  1.185
23  LIF-244  1.229
24  LIF-245  1.074
25  LIF-245  1.077
26  LIF-246  1.466
27  LIF-246  1.604
28  LIF-247  1.438
29  LIF-247  1.401
..      ...    ...
42  LIF-254  1.114
43  LIF-254  1.125
44  LIF-255  1.092
45  LIF-255  1.059
46  LIF-256  1.124
47  LIF-256  1.102
48  LIF-257  1.208
49  LIF-257  1.279
50  LIF-258  0.674
51  LIF-258  0.681
52  LIF-259  0.663
53  LIF-259  0.672
54  LIF-260  0.824
55  LIF-260  0.794
56  LIF-261  0.648
57  LIF-261  0.675
58  LIF-262  0.759
59  LIF-262  0.792
60  LIF-263  0.562
61  LIF-263  1.099
62  LIF-264  0.871
63  LIF-264  0.847
64  LIF-265  0.944
65  LIF-265  0.951
66  LIF-266  0.785
67  LIF-266  0.780
68  LIF-267  0.665
69  LIF-267  0.659
70  LIF-268  0.968
71  LIF-268  0.969

[72 rows x 2 columns]

In [31]:
result=df.merge(df2,on='A')

result.rename(columns = {'B_y':'Mean', 'B_x':'B'}, inplace=True)

print(result)

          A      B      Mean
0       1_1  0.004  0.004000
1       1_2  0.003  0.003000
2       2_1  0.001  0.001000
3       2_2  0.003  0.003000
4         0  0.006  0.006000
5         0  0.006  0.006000
6         0  0.006  0.006000
7      1500  0.166  0.167667
8      1500  0.171  0.167667
9      1500  0.166  0.167667
10     3000  0.302  0.300333
11     3000  0.300  0.300333
12     3000  0.299  0.300333
13     4500  0.437  0.476667
14     4500  0.448  0.476667
15     4500  0.545  0.476667
16  LIF-241  1.181  1.187000
17  LIF-241  1.193  1.187000
18  LIF-242  1.101  1.122000
19  LIF-242  1.143  1.122000
20  LIF-243  1.414  1.390500
21  LIF-243  1.367  1.390500
22  LIF-244  1.185  1.207000
23  LIF-244  1.229  1.207000
24  LIF-245  1.074  1.075500
25  LIF-245  1.077  1.075500
26  LIF-246  1.466  1.535000
27  LIF-246  1.604  1.535000
28  LIF-247  1.438  1.419500
29  LIF-247  1.401  1.419500
..      ...    ...       ...
42  LIF-254  1.114  1.119500
43  LIF-254  1.125  1.119500
44  LIF-255  1.092  1.075500
45  LIF-255  1.059  1.075500
46  LIF-256  1.124  1.113000
47  LIF-256  1.102  1.113000
48  LIF-257  1.208  1.243500
49  LIF-257  1.279  1.243500
50  LIF-258  0.674  0.677500
51  LIF-258  0.681  0.677500
52  LIF-259  0.663  0.667500
53  LIF-259  0.672  0.667500
54  LIF-260  0.824  0.809000
55  LIF-260  0.794  0.809000
56  LIF-261  0.648  0.661500
57  LIF-261  0.675  0.661500
58  LIF-262  0.759  0.775500
59  LIF-262  0.792  0.775500
60  LIF-263  0.562  0.830500
61  LIF-263  1.099  0.830500
62  LIF-264  0.871  0.859000
63  LIF-264  0.847  0.859000
64  LIF-265  0.944  0.947500
65  LIF-265  0.951  0.947500
66  LIF-266  0.785  0.782500
67  LIF-266  0.780  0.782500
68  LIF-267  0.665  0.662000
69  LIF-267  0.659  0.662000
70  LIF-268  0.968  0.968500
71  LIF-268  0.969  0.968500

[72 rows x 3 columns]

In [33]:
## decided to try merging table from g without having to create and import a new csv

final=df.merge(g.mean(),on='A')
print(final)

## SUCCESS!!

          A    B_x       B_y
0       1_1  0.004  0.004000
1       1_2  0.003  0.003000
2       2_1  0.001  0.001000
3       2_2  0.003  0.003000
4         0  0.006  0.006000
5         0  0.006  0.006000
6         0  0.006  0.006000
7      1500  0.166  0.167667
8      1500  0.171  0.167667
9      1500  0.166  0.167667
10     3000  0.302  0.300333
11     3000  0.300  0.300333
12     3000  0.299  0.300333
13     4500  0.437  0.476667
14     4500  0.448  0.476667
15     4500  0.545  0.476667
16  LIF-241  1.181  1.187000
17  LIF-241  1.193  1.187000
18  LIF-242  1.101  1.122000
19  LIF-242  1.143  1.122000
20  LIF-243  1.414  1.390500
21  LIF-243  1.367  1.390500
22  LIF-244  1.185  1.207000
23  LIF-244  1.229  1.207000
24  LIF-245  1.074  1.075500
25  LIF-245  1.077  1.075500
26  LIF-246  1.466  1.535000
27  LIF-246  1.604  1.535000
28  LIF-247  1.438  1.419500
29  LIF-247  1.401  1.419500
..      ...    ...       ...
42  LIF-254  1.114  1.119500
43  LIF-254  1.125  1.119500
44  LIF-255  1.092  1.075500
45  LIF-255  1.059  1.075500
46  LIF-256  1.124  1.113000
47  LIF-256  1.102  1.113000
48  LIF-257  1.208  1.243500
49  LIF-257  1.279  1.243500
50  LIF-258  0.674  0.677500
51  LIF-258  0.681  0.677500
52  LIF-259  0.663  0.667500
53  LIF-259  0.672  0.667500
54  LIF-260  0.824  0.809000
55  LIF-260  0.794  0.809000
56  LIF-261  0.648  0.661500
57  LIF-261  0.675  0.661500
58  LIF-262  0.759  0.775500
59  LIF-262  0.792  0.775500
60  LIF-263  0.562  0.830500
61  LIF-263  1.099  0.830500
62  LIF-264  0.871  0.859000
63  LIF-264  0.847  0.859000
64  LIF-265  0.944  0.947500
65  LIF-265  0.951  0.947500
66  LIF-266  0.785  0.782500
67  LIF-266  0.780  0.782500
68  LIF-267  0.665  0.662000
69  LIF-267  0.659  0.662000
70  LIF-268  0.968  0.968500
71  LIF-268  0.969  0.968500

[72 rows x 3 columns]