In [161]:
## Start pandas

import pandas as pd

## import dataframe csv

df = pd.read_csv('LIF Ashland Nit 12-13-18.csv')

print(type(df))

## group csv by desired column

g = df.groupby('Sample Name')

## TO LIST EACH GROUP SEPARATELY...

for key, item in g:
    print(g.get_group(key), "\n\n")

<class 'pandas.core.frame.DataFrame'>
  Sample Name  410 nm   [A]
4           0         0.006
5           0         0.006
6           0         0.006


  Sample Name  410 nm   [A]
7        1500         0.166
8        1500         0.171
9        1500         0.166


  Sample Name  410 nm   [A]
0         1_1         0.004


  Sample Name  410 nm   [A]
1         1_2         0.003


  Sample Name  410 nm   [A]
2         2_1         0.001


  Sample Name  410 nm   [A]
3         2_2         0.003


   Sample Name  410 nm   [A]
10        3000         0.302
11        3000         0.300
12        3000         0.299


   Sample Name  410 nm   [A]
13        4500         0.437
14        4500         0.448
15        4500         0.545


   Sample Name  410 nm   [A]
16     LIF-241         1.181
17     LIF-241         1.193


   Sample Name  410 nm   [A]
18     LIF-242         1.101
19     LIF-242         1.143


   Sample Name  410 nm   [A]
20     LIF-243         1.414
21     LIF-243         1.367


   Sample Name  410 nm   [A]
22     LIF-244         1.185
23     LIF-244         1.229


   Sample Name  410 nm   [A]
24     LIF-245         1.074
25     LIF-245         1.077


   Sample Name  410 nm   [A]
26     LIF-246         1.466
27     LIF-246         1.604


   Sample Name  410 nm   [A]
28     LIF-247         1.438
29     LIF-247         1.401


   Sample Name  410 nm   [A]
30     LIF-248         1.564
31     LIF-248         1.575


   Sample Name  410 nm   [A]
32     LIF-249         1.282
33     LIF-249         1.302


   Sample Name  410 nm   [A]
34     LIF-250         1.038
35     LIF-250         1.125


   Sample Name  410 nm   [A]
36     LIF-251         1.226
37     LIF-251         1.128


   Sample Name  410 nm   [A]
38     LIF-252         1.256
39     LIF-252         1.184


   Sample Name  410 nm   [A]
40     LIF-253         1.335
41     LIF-253         1.462


   Sample Name  410 nm   [A]
42     LIF-254         1.114
43     LIF-254         1.125


   Sample Name  410 nm   [A]
44     LIF-255         1.092
45     LIF-255         1.059


   Sample Name  410 nm   [A]
46     LIF-256         1.124
47     LIF-256         1.102


   Sample Name  410 nm   [A]
48     LIF-257         1.208
49     LIF-257         1.279


   Sample Name  410 nm   [A]
50     LIF-258         0.674
51     LIF-258         0.681


   Sample Name  410 nm   [A]
52     LIF-259         0.663
53     LIF-259         0.672


   Sample Name  410 nm   [A]
54     LIF-260         0.824
55     LIF-260         0.794


   Sample Name  410 nm   [A]
56     LIF-261         0.648
57     LIF-261         0.675


   Sample Name  410 nm   [A]
58     LIF-262         0.759
59     LIF-262         0.792


   Sample Name  410 nm   [A]
60     LIF-263         0.562
61     LIF-263         1.099


   Sample Name  410 nm   [A]
62     LIF-264         0.871
63     LIF-264         0.847


   Sample Name  410 nm   [A]
64     LIF-265         0.944
65     LIF-265         0.951


   Sample Name  410 nm   [A]
66     LIF-266         0.785
67     LIF-266         0.780


   Sample Name  410 nm   [A]
68     LIF-267         0.665
69     LIF-267         0.659


   Sample Name  410 nm   [A]
70     LIF-268         0.968
71     LIF-268         0.969

In [94]:
### renaming columns
## to display columns

df['C'] = (g.mean())

In [95]:
## using rename function, assign new names to each column, and direct program with final command

df.rename(columns = {'Sample Name':'A', '410 nm   [A]':'B'}, inplace=True)
df

          A      B   C
0       1_1  0.004 NaN
1       1_2  0.003 NaN
2       2_1  0.001 NaN
3       2_2  0.003 NaN
4         0  0.006 NaN
5         0  0.006 NaN
6         0  0.006 NaN
7      1500  0.166 NaN
8      1500  0.171 NaN
9      1500  0.166 NaN
10     3000  0.302 NaN
11     3000  0.300 NaN
12     3000  0.299 NaN
13     4500  0.437 NaN
14     4500  0.448 NaN
15     4500  0.545 NaN
16  LIF-241  1.181 NaN
17  LIF-241  1.193 NaN
18  LIF-242  1.101 NaN
19  LIF-242  1.143 NaN
20  LIF-243  1.414 NaN
21  LIF-243  1.367 NaN
22  LIF-244  1.185 NaN
23  LIF-244  1.229 NaN
24  LIF-245  1.074 NaN
25  LIF-245  1.077 NaN
26  LIF-246  1.466 NaN
27  LIF-246  1.604 NaN
28  LIF-247  1.438 NaN
29  LIF-247  1.401 NaN
..      ...    ...  ..
42  LIF-254  1.114 NaN
43  LIF-254  1.125 NaN
44  LIF-255  1.092 NaN
45  LIF-255  1.059 NaN
46  LIF-256  1.124 NaN
47  LIF-256  1.102 NaN
48  LIF-257  1.208 NaN
49  LIF-257  1.279 NaN
50  LIF-258  0.674 NaN
51  LIF-258  0.681 NaN
52  LIF-259  0.663 NaN
53  LIF-259  0.672 NaN
54  LIF-260  0.824 NaN
55  LIF-260  0.794 NaN
56  LIF-261  0.648 NaN
57  LIF-261  0.675 NaN
58  LIF-262  0.759 NaN
59  LIF-262  0.792 NaN
60  LIF-263  0.562 NaN
61  LIF-263  1.099 NaN
62  LIF-264  0.871 NaN
63  LIF-264  0.847 NaN
64  LIF-265  0.944 NaN
65  LIF-265  0.951 NaN
66  LIF-266  0.785 NaN
67  LIF-266  0.780 NaN
68  LIF-267  0.665 NaN
69  LIF-267  0.659 NaN
70  LIF-268  0.968 NaN
71  LIF-268  0.969 NaN

[72 rows x 3 columns]

In [86]:
('C')

NameError: name 'delete' is not defined

In [126]:
## group csv by desired column

g = df.groupby('A')

                   
## TO LIST EACH GROUP SEPARATELY...

for key, item in g:
  print(g.get_group(key), "\n\n"),

   A      B   C
4  0  0.006 NaN
5  0  0.006 NaN
6  0  0.006 NaN


      A      B   C
7  1500  0.166 NaN
8  1500  0.171 NaN
9  1500  0.166 NaN


     A      B   C
0  1_1  0.004 NaN


     A      B   C
1  1_2  0.003 NaN


     A      B   C
2  2_1  0.001 NaN


     A      B   C
3  2_2  0.003 NaN


       A      B   C
10  3000  0.302 NaN
11  3000  0.300 NaN
12  3000  0.299 NaN


       A      B   C
13  4500  0.437 NaN
14  4500  0.448 NaN
15  4500  0.545 NaN


          A      B   C
16  LIF-241  1.181 NaN
17  LIF-241  1.193 NaN


          A      B   C
18  LIF-242  1.101 NaN
19  LIF-242  1.143 NaN


          A      B   C
20  LIF-243  1.414 NaN
21  LIF-243  1.367 NaN


          A      B   C
22  LIF-244  1.185 NaN
23  LIF-244  1.229 NaN


          A      B   C
24  LIF-245  1.074 NaN
25  LIF-245  1.077 NaN


          A      B   C
26  LIF-246  1.466 NaN
27  LIF-246  1.604 NaN


          A      B   C
28  LIF-247  1.438 NaN
29  LIF-247  1.401 NaN


          A      B   C
30  LIF-248  1.564 NaN
31  LIF-248  1.575 NaN


          A      B   C
32  LIF-249  1.282 NaN
33  LIF-249  1.302 NaN


          A      B   C
34  LIF-250  1.038 NaN
35  LIF-250  1.125 NaN


          A      B   C
36  LIF-251  1.226 NaN
37  LIF-251  1.128 NaN


          A      B   C
38  LIF-252  1.256 NaN
39  LIF-252  1.184 NaN


          A      B   C
40  LIF-253  1.335 NaN
41  LIF-253  1.462 NaN


          A      B   C
42  LIF-254  1.114 NaN
43  LIF-254  1.125 NaN


          A      B   C
44  LIF-255  1.092 NaN
45  LIF-255  1.059 NaN


          A      B   C
46  LIF-256  1.124 NaN
47  LIF-256  1.102 NaN


          A      B   C
48  LIF-257  1.208 NaN
49  LIF-257  1.279 NaN


          A      B   C
50  LIF-258  0.674 NaN
51  LIF-258  0.681 NaN


          A      B   C
52  LIF-259  0.663 NaN
53  LIF-259  0.672 NaN


          A      B   C
54  LIF-260  0.824 NaN
55  LIF-260  0.794 NaN


          A      B   C
56  LIF-261  0.648 NaN
57  LIF-261  0.675 NaN


          A      B   C
58  LIF-262  0.759 NaN
59  LIF-262  0.792 NaN


          A      B   C
60  LIF-263  0.562 NaN
61  LIF-263  1.099 NaN


          A      B   C
62  LIF-264  0.871 NaN
63  LIF-264  0.847 NaN


          A      B   C
64  LIF-265  0.944 NaN
65  LIF-265  0.951 NaN


          A      B   C
66  LIF-266  0.785 NaN
67  LIF-266  0.780 NaN


          A      B   C
68  LIF-267  0.665 NaN
69  LIF-267  0.659 NaN


          A      B   C
70  LIF-268  0.968 NaN
71  LIF-268  0.969 NaN

In [157]:
## Trying to call a conditional based on the difference between sample values
## if good, display mean
## if bad, display "error" message

for key, item in g:
    if (g.first() - g.last()/g.first()).float >= 0.1:
        print('Yes')
    else:
        print('No')

AttributeError: 'DataFrame' object has no attribute 'float'